/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`


import com.arbr.db.DefaultCatalog

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.alpha_code</code>.
     */
    val ALPHA_CODE: com.arbr.db.`public`.tables.AlphaCode get() = com.arbr.db.`public`.tables.AlphaCode.ALPHA_CODE

    /**
     * The table <code>public.application_completion</code>.
     */
    val APPLICATION_COMPLETION: com.arbr.db.`public`.tables.ApplicationCompletion get() = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION

    /**
     * The table <code>public.embedded_content</code>.
     */
    val EMBEDDED_CONTENT: com.arbr.db.`public`.tables.EmbeddedContent get() = com.arbr.db.`public`.tables.EmbeddedContent.EMBEDDED_CONTENT

    /**
     * Input-Output pairs of Embedded Resources
     */
    val EMBEDDED_RESOURCE_PAIR: com.arbr.db.`public`.tables.EmbeddedResourcePair get() = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR

    /**
     * The table <code>public.indexed_resource</code>.
     */
    val INDEXED_RESOURCE: com.arbr.db.`public`.tables.IndexedResource get() = com.arbr.db.`public`.tables.IndexedResource.INDEXED_RESOURCE

    /**
     * The table <code>public.io_pair</code>.
     */
    val IO_PAIR: com.arbr.db.`public`.tables.IoPair get() = com.arbr.db.`public`.tables.IoPair.IO_PAIR

    /**
     * The table <code>public.user_account</code>.
     */
    val USER_ACCOUNT: com.arbr.db.`public`.tables.UserAccount get() = com.arbr.db.`public`.tables.UserAccount.USER_ACCOUNT

    /**
     * The table <code>public.user_account_link_alpha_code</code>.
     */
    val USER_ACCOUNT_LINK_ALPHA_CODE: com.arbr.db.`public`.tables.UserAccountLinkAlphaCode get() = com.arbr.db.`public`.tables.UserAccountLinkAlphaCode.USER_ACCOUNT_LINK_ALPHA_CODE

    /**
     * The table <code>public.user_account_link_github</code>.
     */
    val USER_ACCOUNT_LINK_GITHUB: com.arbr.db.`public`.tables.UserAccountLinkGithub get() = com.arbr.db.`public`.tables.UserAccountLinkGithub.USER_ACCOUNT_LINK_GITHUB

    /**
     * The table <code>public.user_email</code>.
     */
    val USER_EMAIL: com.arbr.db.`public`.tables.UserEmail get() = com.arbr.db.`public`.tables.UserEmail.USER_EMAIL

    /**
     * The table <code>public.user_event</code>.
     */
    val USER_EVENT: com.arbr.db.`public`.tables.UserEvent get() = com.arbr.db.`public`.tables.UserEvent.USER_EVENT

    /**
     * The table <code>public.user_project</code>.
     */
    val USER_PROJECT: com.arbr.db.`public`.tables.UserProject get() = com.arbr.db.`public`.tables.UserProject.USER_PROJECT

    /**
     * The table <code>public.user_project_workflow</code>.
     */
    val USER_PROJECT_WORKFLOW: com.arbr.db.`public`.tables.UserProjectWorkflow get() = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW

    /**
     * The table <code>public.user_project_workflow_event_stream</code>.
     */
    val USER_PROJECT_WORKFLOW_EVENT_STREAM: com.arbr.db.`public`.tables.UserProjectWorkflowEventStream get() = com.arbr.db.`public`.tables.UserProjectWorkflowEventStream.USER_PROJECT_WORKFLOW_EVENT_STREAM

    /**
     * The table <code>public.user_project_workflow_resource</code>.
     */
    val USER_PROJECT_WORKFLOW_RESOURCE: com.arbr.db.`public`.tables.UserProjectWorkflowResource get() = com.arbr.db.`public`.tables.UserProjectWorkflowResource.USER_PROJECT_WORKFLOW_RESOURCE

    /**
     * The table <code>public.user_project_workflow_worker</code>.
     */
    val USER_PROJECT_WORKFLOW_WORKER: com.arbr.db.`public`.tables.UserProjectWorkflowWorker get() = com.arbr.db.`public`.tables.UserProjectWorkflowWorker.USER_PROJECT_WORKFLOW_WORKER

    /**
     * The table <code>public.vector_embedding</code>.
     */
    val VECTOR_EMBEDDING: com.arbr.db.`public`.tables.VectorEmbedding get() = com.arbr.db.`public`.tables.VectorEmbedding.VECTOR_EMBEDDING

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        com.arbr.db.`public`.tables.AlphaCode.ALPHA_CODE,
        com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION,
        com.arbr.db.`public`.tables.EmbeddedContent.EMBEDDED_CONTENT,
        com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR,
        com.arbr.db.`public`.tables.IndexedResource.INDEXED_RESOURCE,
        com.arbr.db.`public`.tables.IoPair.IO_PAIR,
        com.arbr.db.`public`.tables.UserAccount.USER_ACCOUNT,
        com.arbr.db.`public`.tables.UserAccountLinkAlphaCode.USER_ACCOUNT_LINK_ALPHA_CODE,
        com.arbr.db.`public`.tables.UserAccountLinkGithub.USER_ACCOUNT_LINK_GITHUB,
        com.arbr.db.`public`.tables.UserEmail.USER_EMAIL,
        com.arbr.db.`public`.tables.UserEvent.USER_EVENT,
        com.arbr.db.`public`.tables.UserProject.USER_PROJECT,
        com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW,
        com.arbr.db.`public`.tables.UserProjectWorkflowEventStream.USER_PROJECT_WORKFLOW_EVENT_STREAM,
        com.arbr.db.`public`.tables.UserProjectWorkflowResource.USER_PROJECT_WORKFLOW_RESOURCE,
        com.arbr.db.`public`.tables.UserProjectWorkflowWorker.USER_PROJECT_WORKFLOW_WORKER,
        com.arbr.db.`public`.tables.VectorEmbedding.VECTOR_EMBEDDING
    )
}
