load("@rules_kotlin//kotlin:core.bzl", "kt_compiler_plugin")
load("@rules_kotlin//kotlin/internal:toolchains.bzl", "define_kt_toolchain")

define_kt_toolchain(
    name = "arbr_kt_toolchain",
    api_version = "1.9",
    jvm_target = "21",
    language_version = "1.9",
)

#
# `kotlin` support
#

kt_compiler_plugin(
    name = "allopen_plugin",
    compile_phase = True,
    id = "org.jetbrains.kotlin.allopen",
    options = {
        "annotation": "org.springframework.stereotype.Component",
        "preset": "spring",
    },
    stubs_phase = True,
    visibility = ["//visibility:public"],
    deps = [
        "@rules_kotlin//kotlin/compiler:allopen-compiler-plugin",
    ],
)
