/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.indexes


import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val EMBEDDED_CONTENT_VECTOR_ID: Index = Internal.createIndex(DSL.name("embedded_content_vector_id"), com.arbr.db.`public`.tables.EmbeddedContent.EMBEDDED_CONTENT, arrayOf(com.arbr.db.`public`.tables.EmbeddedContent.EMBEDDED_CONTENT.VECTOR_ID), false)
val IO_PAIR_INPUT_RESOURCE_ID: Index = Internal.createIndex(DSL.name("io_pair_input_resource_id"), com.arbr.db.`public`.tables.IoPair.IO_PAIR, arrayOf(com.arbr.db.`public`.tables.IoPair.IO_PAIR.INPUT_RESOURCE_ID), false)
val USER_EMAIL_EMAIL_ADDRESS: Index = Internal.createIndex(DSL.name("user_email_email_address"), com.arbr.db.`public`.tables.UserEmail.USER_EMAIL, arrayOf(com.arbr.db.`public`.tables.UserEmail.USER_EMAIL.EMAIL_ADDRESS), false)
val USER_EMAIL_USER_ID: Index = Internal.createIndex(DSL.name("user_email_user_id"), com.arbr.db.`public`.tables.UserEmail.USER_EMAIL, arrayOf(com.arbr.db.`public`.tables.UserEmail.USER_EMAIL.USER_ID), false)
val USER_EVENT_USER_ID: Index = Internal.createIndex(DSL.name("user_event_user_id"), com.arbr.db.`public`.tables.UserEvent.USER_EVENT, arrayOf(com.arbr.db.`public`.tables.UserEvent.USER_EVENT.USER_ID), false)
val USER_PROJECT_ID_IDX: Index = Internal.createIndex(DSL.name("user_project_id_idx"), com.arbr.db.`public`.tables.UserProject.USER_PROJECT, arrayOf(com.arbr.db.`public`.tables.UserProject.USER_PROJECT.ID), false)
val USER_PROJECT_WORKFLOW_EVENT_STREAM_OFFSET_IDX: Index = Internal.createIndex(DSL.name("user_project_workflow_event_stream_offset_idx"), com.arbr.db.`public`.tables.UserProjectWorkflowEventStream.USER_PROJECT_WORKFLOW_EVENT_STREAM, arrayOf(com.arbr.db.`public`.tables.UserProjectWorkflowEventStream.USER_PROJECT_WORKFLOW_EVENT_STREAM.ORDINAL_OFFSET), false)
val USER_PROJECT_WORKFLOW_EVENT_STREAM_STATE_HASH_IDX: Index = Internal.createIndex(DSL.name("user_project_workflow_event_stream_state_hash_idx"), com.arbr.db.`public`.tables.UserProjectWorkflowEventStream.USER_PROJECT_WORKFLOW_EVENT_STREAM, arrayOf(com.arbr.db.`public`.tables.UserProjectWorkflowEventStream.USER_PROJECT_WORKFLOW_EVENT_STREAM.STATE_HASH), false)
val USER_PROJECT_WORKFLOW_EVENT_STREAM_TOPIC_NAME_IDX: Index = Internal.createIndex(DSL.name("user_project_workflow_event_stream_topic_name_idx"), com.arbr.db.`public`.tables.UserProjectWorkflowEventStream.USER_PROJECT_WORKFLOW_EVENT_STREAM, arrayOf(com.arbr.db.`public`.tables.UserProjectWorkflowEventStream.USER_PROJECT_WORKFLOW_EVENT_STREAM.TOPIC_NAME), false)
val USER_PROJECT_WORKFLOW_EVENT_STREAM_WORKFLOW_ID_IDX: Index = Internal.createIndex(DSL.name("user_project_workflow_event_stream_workflow_id_idx"), com.arbr.db.`public`.tables.UserProjectWorkflowEventStream.USER_PROJECT_WORKFLOW_EVENT_STREAM, arrayOf(com.arbr.db.`public`.tables.UserProjectWorkflowEventStream.USER_PROJECT_WORKFLOW_EVENT_STREAM.WORKFLOW_ID), false)
val USER_PROJECT_WORKFLOW_ID_IDX: Index = Internal.createIndex(DSL.name("user_project_workflow_id_idx"), com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW, arrayOf(com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.ID), false)
val USER_PROJECT_WORKFLOW_PROJECT_ID_IDX: Index = Internal.createIndex(DSL.name("user_project_workflow_project_id_idx"), com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW, arrayOf(com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.PROJECT_ID), false)
val USER_PROJECT_WORKFLOW_RESOURCE_UUID_IDX: Index = Internal.createIndex(DSL.name("user_project_workflow_resource_uuid_idx"), com.arbr.db.`public`.tables.UserProjectWorkflowResource.USER_PROJECT_WORKFLOW_RESOURCE, arrayOf(com.arbr.db.`public`.tables.UserProjectWorkflowResource.USER_PROJECT_WORKFLOW_RESOURCE.OBJECT_MODEL_UUID), false)
val USER_PROJECT_WORKFLOW_RESOURCE_WORKFLOW_ID_IDX: Index = Internal.createIndex(DSL.name("user_project_workflow_resource_workflow_id_idx"), com.arbr.db.`public`.tables.UserProjectWorkflowResource.USER_PROJECT_WORKFLOW_RESOURCE, arrayOf(com.arbr.db.`public`.tables.UserProjectWorkflowResource.USER_PROJECT_WORKFLOW_RESOURCE.WORKFLOW_ID), false)
