/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.records


import org.jooq.Field
import org.jooq.Record1
import org.jooq.Row1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AlphaCodeRecord private constructor() : UpdatableRecordImpl<AlphaCodeRecord>(com.arbr.db.`public`.tables.AlphaCode.ALPHA_CODE), Record1<String?> {

    open var code: String
        set(value): Unit = set(0, value)
        get(): String = get(0) as String

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row1<String?> = super.fieldsRow() as Row1<String?>
    override fun valuesRow(): Row1<String?> = super.valuesRow() as Row1<String?>
    override fun field1(): Field<String?> = com.arbr.db.`public`.tables.AlphaCode.ALPHA_CODE.CODE
    override fun component1(): String = code
    override fun value1(): String = code

    override fun value1(value: String?): AlphaCodeRecord {
        set(0, value)
        return this
    }

    override fun values(value1: String?): AlphaCodeRecord {
        this.value1(value1)
        return this
    }

    /**
     * Create a detached, initialised AlphaCodeRecord
     */
    constructor(code: String): this() {
        this.code = code
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised AlphaCodeRecord
     */
    constructor(value: com.arbr.db.`public`.tables.pojos.AlphaCode?): this() {
        if (value != null) {
            this.code = value.code
            resetChangedOnNotNull()
        }
    }
}
