/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.records


import org.jooq.Field
import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.Record14
import org.jooq.Row14
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ApplicationCompletionRecord private constructor() : UpdatableRecordImpl<ApplicationCompletionRecord>(com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION), Record14<String?, Long?, String?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, Long?, String?, Long?, Long?, Long?> {

    open var cacheKey: String
        set(value): Unit = set(0, value)
        get(): String = get(0) as String

    open var creationTimestamp: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open var applicationId: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var exampleVectorIds: JSONB
        set(value): Unit = set(3, value)
        get(): JSONB = get(3) as JSONB

    open var inputVectorIds: JSONB
        set(value): Unit = set(4, value)
        get(): JSONB = get(4) as JSONB

    open var inputResource: JSONB
        set(value): Unit = set(5, value)
        get(): JSONB = get(5) as JSONB

    open var outputResource: JSONB
        set(value): Unit = set(6, value)
        get(): JSONB = get(6) as JSONB

    open var promptMessages: JSONB
        set(value): Unit = set(7, value)
        get(): JSONB = get(7) as JSONB

    open var completionMessages: JSONB?
        set(value): Unit = set(8, value)
        get(): JSONB? = get(8) as JSONB?

    open var workflowId: Long?
        set(value): Unit = set(9, value)
        get(): Long? = get(9) as Long?

    open var usedModel: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var promptTokens: Long?
        set(value): Unit = set(11, value)
        get(): Long? = get(11) as Long?

    open var completionTokens: Long?
        set(value): Unit = set(12, value)
        get(): Long? = get(12) as Long?

    open var totalTokens: Long?
        set(value): Unit = set(13, value)
        get(): Long? = get(13) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row14<String?, Long?, String?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, Long?, String?, Long?, Long?, Long?> = super.fieldsRow() as Row14<String?, Long?, String?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, Long?, String?, Long?, Long?, Long?>
    override fun valuesRow(): Row14<String?, Long?, String?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, Long?, String?, Long?, Long?, Long?> = super.valuesRow() as Row14<String?, Long?, String?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, Long?, String?, Long?, Long?, Long?>
    override fun field1(): Field<String?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.CACHE_KEY
    override fun field2(): Field<Long?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.CREATION_TIMESTAMP
    override fun field3(): Field<String?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.APPLICATION_ID
    override fun field4(): Field<JSONB?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.EXAMPLE_VECTOR_IDS
    override fun field5(): Field<JSONB?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.INPUT_VECTOR_IDS
    override fun field6(): Field<JSONB?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.INPUT_RESOURCE
    override fun field7(): Field<JSONB?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.OUTPUT_RESOURCE
    override fun field8(): Field<JSONB?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.PROMPT_MESSAGES
    override fun field9(): Field<JSONB?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.COMPLETION_MESSAGES
    override fun field10(): Field<Long?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.WORKFLOW_ID
    override fun field11(): Field<String?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.USED_MODEL
    override fun field12(): Field<Long?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.PROMPT_TOKENS
    override fun field13(): Field<Long?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.COMPLETION_TOKENS
    override fun field14(): Field<Long?> = com.arbr.db.`public`.tables.ApplicationCompletion.APPLICATION_COMPLETION.TOTAL_TOKENS
    override fun component1(): String = cacheKey
    override fun component2(): Long = creationTimestamp
    override fun component3(): String = applicationId
    override fun component4(): JSONB = exampleVectorIds
    override fun component5(): JSONB = inputVectorIds
    override fun component6(): JSONB = inputResource
    override fun component7(): JSONB = outputResource
    override fun component8(): JSONB = promptMessages
    override fun component9(): JSONB? = completionMessages
    override fun component10(): Long? = workflowId
    override fun component11(): String? = usedModel
    override fun component12(): Long? = promptTokens
    override fun component13(): Long? = completionTokens
    override fun component14(): Long? = totalTokens
    override fun value1(): String = cacheKey
    override fun value2(): Long = creationTimestamp
    override fun value3(): String = applicationId
    override fun value4(): JSONB = exampleVectorIds
    override fun value5(): JSONB = inputVectorIds
    override fun value6(): JSONB = inputResource
    override fun value7(): JSONB = outputResource
    override fun value8(): JSONB = promptMessages
    override fun value9(): JSONB? = completionMessages
    override fun value10(): Long? = workflowId
    override fun value11(): String? = usedModel
    override fun value12(): Long? = promptTokens
    override fun value13(): Long? = completionTokens
    override fun value14(): Long? = totalTokens

    override fun value1(value: String?): ApplicationCompletionRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Long?): ApplicationCompletionRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): ApplicationCompletionRecord {
        set(2, value)
        return this
    }

    override fun value4(value: JSONB?): ApplicationCompletionRecord {
        set(3, value)
        return this
    }

    override fun value5(value: JSONB?): ApplicationCompletionRecord {
        set(4, value)
        return this
    }

    override fun value6(value: JSONB?): ApplicationCompletionRecord {
        set(5, value)
        return this
    }

    override fun value7(value: JSONB?): ApplicationCompletionRecord {
        set(6, value)
        return this
    }

    override fun value8(value: JSONB?): ApplicationCompletionRecord {
        set(7, value)
        return this
    }

    override fun value9(value: JSONB?): ApplicationCompletionRecord {
        set(8, value)
        return this
    }

    override fun value10(value: Long?): ApplicationCompletionRecord {
        set(9, value)
        return this
    }

    override fun value11(value: String?): ApplicationCompletionRecord {
        set(10, value)
        return this
    }

    override fun value12(value: Long?): ApplicationCompletionRecord {
        set(11, value)
        return this
    }

    override fun value13(value: Long?): ApplicationCompletionRecord {
        set(12, value)
        return this
    }

    override fun value14(value: Long?): ApplicationCompletionRecord {
        set(13, value)
        return this
    }

    override fun values(value1: String?, value2: Long?, value3: String?, value4: JSONB?, value5: JSONB?, value6: JSONB?, value7: JSONB?, value8: JSONB?, value9: JSONB?, value10: Long?, value11: String?, value12: Long?, value13: Long?, value14: Long?): ApplicationCompletionRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        return this
    }

    /**
     * Create a detached, initialised ApplicationCompletionRecord
     */
    constructor(cacheKey: String, creationTimestamp: Long, applicationId: String, exampleVectorIds: JSONB, inputVectorIds: JSONB, inputResource: JSONB, outputResource: JSONB, promptMessages: JSONB, completionMessages: JSONB? = null, workflowId: Long? = null, usedModel: String? = null, promptTokens: Long? = null, completionTokens: Long? = null, totalTokens: Long? = null): this() {
        this.cacheKey = cacheKey
        this.creationTimestamp = creationTimestamp
        this.applicationId = applicationId
        this.exampleVectorIds = exampleVectorIds
        this.inputVectorIds = inputVectorIds
        this.inputResource = inputResource
        this.outputResource = outputResource
        this.promptMessages = promptMessages
        this.completionMessages = completionMessages
        this.workflowId = workflowId
        this.usedModel = usedModel
        this.promptTokens = promptTokens
        this.completionTokens = completionTokens
        this.totalTokens = totalTokens
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised ApplicationCompletionRecord
     */
    constructor(value: com.arbr.db.`public`.tables.pojos.ApplicationCompletion?): this() {
        if (value != null) {
            this.cacheKey = value.cacheKey
            this.creationTimestamp = value.creationTimestamp
            this.applicationId = value.applicationId
            this.exampleVectorIds = value.exampleVectorIds
            this.inputVectorIds = value.inputVectorIds
            this.inputResource = value.inputResource
            this.outputResource = value.outputResource
            this.promptMessages = value.promptMessages
            this.completionMessages = value.completionMessages
            this.workflowId = value.workflowId
            this.usedModel = value.usedModel
            this.promptTokens = value.promptTokens
            this.completionTokens = value.completionTokens
            this.totalTokens = value.totalTokens
            resetChangedOnNotNull()
        }
    }
}
