/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.records


import org.jooq.Field
import org.jooq.JSONB
import org.jooq.Record14
import org.jooq.Row14
import org.jooq.impl.TableRecordImpl


/**
 * Input-Output pairs of Embedded Resources
 */
@Suppress("UNCHECKED_CAST")
open class EmbeddedResourcePairRecord private constructor() : TableRecordImpl<EmbeddedResourcePairRecord>(com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR), Record14<Long?, Long?, String?, JSONB?, JSONB?, String?, String?, String?, JSONB?, Long?, Long?, String?, JSONB?, JSONB?> {

    open var inputResourceId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var inputCreationTimestamp: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var inputSchemaId: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var inputResourceObject: JSONB?
        set(value): Unit = set(3, value)
        get(): JSONB? = get(3) as JSONB?

    open var inputChatMessages: JSONB?
        set(value): Unit = set(4, value)
        get(): JSONB? = get(4) as JSONB?

    open var vectorId: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var embeddingKind: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var embeddingContent: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var metadata: JSONB?
        set(value): Unit = set(8, value)
        get(): JSONB? = get(8) as JSONB?

    open var outputResourceId: Long?
        set(value): Unit = set(9, value)
        get(): Long? = get(9) as Long?

    open var outputCreationTimestamp: Long?
        set(value): Unit = set(10, value)
        get(): Long? = get(10) as Long?

    open var outputSchemaId: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var outputResourceObject: JSONB?
        set(value): Unit = set(12, value)
        get(): JSONB? = get(12) as JSONB?

    open var outputChatMessages: JSONB?
        set(value): Unit = set(13, value)
        get(): JSONB? = get(13) as JSONB?

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row14<Long?, Long?, String?, JSONB?, JSONB?, String?, String?, String?, JSONB?, Long?, Long?, String?, JSONB?, JSONB?> = super.fieldsRow() as Row14<Long?, Long?, String?, JSONB?, JSONB?, String?, String?, String?, JSONB?, Long?, Long?, String?, JSONB?, JSONB?>
    override fun valuesRow(): Row14<Long?, Long?, String?, JSONB?, JSONB?, String?, String?, String?, JSONB?, Long?, Long?, String?, JSONB?, JSONB?> = super.valuesRow() as Row14<Long?, Long?, String?, JSONB?, JSONB?, String?, String?, String?, JSONB?, Long?, Long?, String?, JSONB?, JSONB?>
    override fun field1(): Field<Long?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.INPUT_RESOURCE_ID
    override fun field2(): Field<Long?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.INPUT_CREATION_TIMESTAMP
    override fun field3(): Field<String?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.INPUT_SCHEMA_ID
    override fun field4(): Field<JSONB?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.INPUT_RESOURCE_OBJECT
    override fun field5(): Field<JSONB?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.INPUT_CHAT_MESSAGES
    override fun field6(): Field<String?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.VECTOR_ID
    override fun field7(): Field<String?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.EMBEDDING_KIND
    override fun field8(): Field<String?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.EMBEDDING_CONTENT
    override fun field9(): Field<JSONB?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.METADATA
    override fun field10(): Field<Long?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.OUTPUT_RESOURCE_ID
    override fun field11(): Field<Long?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.OUTPUT_CREATION_TIMESTAMP
    override fun field12(): Field<String?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.OUTPUT_SCHEMA_ID
    override fun field13(): Field<JSONB?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.OUTPUT_RESOURCE_OBJECT
    override fun field14(): Field<JSONB?> = com.arbr.db.`public`.tables.EmbeddedResourcePair.EMBEDDED_RESOURCE_PAIR.OUTPUT_CHAT_MESSAGES
    override fun component1(): Long? = inputResourceId
    override fun component2(): Long? = inputCreationTimestamp
    override fun component3(): String? = inputSchemaId
    override fun component4(): JSONB? = inputResourceObject
    override fun component5(): JSONB? = inputChatMessages
    override fun component6(): String? = vectorId
    override fun component7(): String? = embeddingKind
    override fun component8(): String? = embeddingContent
    override fun component9(): JSONB? = metadata
    override fun component10(): Long? = outputResourceId
    override fun component11(): Long? = outputCreationTimestamp
    override fun component12(): String? = outputSchemaId
    override fun component13(): JSONB? = outputResourceObject
    override fun component14(): JSONB? = outputChatMessages
    override fun value1(): Long? = inputResourceId
    override fun value2(): Long? = inputCreationTimestamp
    override fun value3(): String? = inputSchemaId
    override fun value4(): JSONB? = inputResourceObject
    override fun value5(): JSONB? = inputChatMessages
    override fun value6(): String? = vectorId
    override fun value7(): String? = embeddingKind
    override fun value8(): String? = embeddingContent
    override fun value9(): JSONB? = metadata
    override fun value10(): Long? = outputResourceId
    override fun value11(): Long? = outputCreationTimestamp
    override fun value12(): String? = outputSchemaId
    override fun value13(): JSONB? = outputResourceObject
    override fun value14(): JSONB? = outputChatMessages

    override fun value1(value: Long?): EmbeddedResourcePairRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Long?): EmbeddedResourcePairRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): EmbeddedResourcePairRecord {
        set(2, value)
        return this
    }

    override fun value4(value: JSONB?): EmbeddedResourcePairRecord {
        set(3, value)
        return this
    }

    override fun value5(value: JSONB?): EmbeddedResourcePairRecord {
        set(4, value)
        return this
    }

    override fun value6(value: String?): EmbeddedResourcePairRecord {
        set(5, value)
        return this
    }

    override fun value7(value: String?): EmbeddedResourcePairRecord {
        set(6, value)
        return this
    }

    override fun value8(value: String?): EmbeddedResourcePairRecord {
        set(7, value)
        return this
    }

    override fun value9(value: JSONB?): EmbeddedResourcePairRecord {
        set(8, value)
        return this
    }

    override fun value10(value: Long?): EmbeddedResourcePairRecord {
        set(9, value)
        return this
    }

    override fun value11(value: Long?): EmbeddedResourcePairRecord {
        set(10, value)
        return this
    }

    override fun value12(value: String?): EmbeddedResourcePairRecord {
        set(11, value)
        return this
    }

    override fun value13(value: JSONB?): EmbeddedResourcePairRecord {
        set(12, value)
        return this
    }

    override fun value14(value: JSONB?): EmbeddedResourcePairRecord {
        set(13, value)
        return this
    }

    override fun values(value1: Long?, value2: Long?, value3: String?, value4: JSONB?, value5: JSONB?, value6: String?, value7: String?, value8: String?, value9: JSONB?, value10: Long?, value11: Long?, value12: String?, value13: JSONB?, value14: JSONB?): EmbeddedResourcePairRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        return this
    }

    /**
     * Create a detached, initialised EmbeddedResourcePairRecord
     */
    constructor(inputResourceId: Long? = null, inputCreationTimestamp: Long? = null, inputSchemaId: String? = null, inputResourceObject: JSONB? = null, inputChatMessages: JSONB? = null, vectorId: String? = null, embeddingKind: String? = null, embeddingContent: String? = null, metadata: JSONB? = null, outputResourceId: Long? = null, outputCreationTimestamp: Long? = null, outputSchemaId: String? = null, outputResourceObject: JSONB? = null, outputChatMessages: JSONB? = null): this() {
        this.inputResourceId = inputResourceId
        this.inputCreationTimestamp = inputCreationTimestamp
        this.inputSchemaId = inputSchemaId
        this.inputResourceObject = inputResourceObject
        this.inputChatMessages = inputChatMessages
        this.vectorId = vectorId
        this.embeddingKind = embeddingKind
        this.embeddingContent = embeddingContent
        this.metadata = metadata
        this.outputResourceId = outputResourceId
        this.outputCreationTimestamp = outputCreationTimestamp
        this.outputSchemaId = outputSchemaId
        this.outputResourceObject = outputResourceObject
        this.outputChatMessages = outputChatMessages
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised EmbeddedResourcePairRecord
     */
    constructor(value: com.arbr.db.`public`.tables.pojos.EmbeddedResourcePair?): this() {
        if (value != null) {
            this.inputResourceId = value.inputResourceId
            this.inputCreationTimestamp = value.inputCreationTimestamp
            this.inputSchemaId = value.inputSchemaId
            this.inputResourceObject = value.inputResourceObject
            this.inputChatMessages = value.inputChatMessages
            this.vectorId = value.vectorId
            this.embeddingKind = value.embeddingKind
            this.embeddingContent = value.embeddingContent
            this.metadata = value.metadata
            this.outputResourceId = value.outputResourceId
            this.outputCreationTimestamp = value.outputCreationTimestamp
            this.outputSchemaId = value.outputSchemaId
            this.outputResourceObject = value.outputResourceObject
            this.outputChatMessages = value.outputChatMessages
            resetChangedOnNotNull()
        }
    }
}
