/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.records


import org.jooq.Field
import org.jooq.JSONB
import org.jooq.Record13
import org.jooq.Row13
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserProjectWorkflowRecord private constructor() : TableRecordImpl<UserProjectWorkflowRecord>(com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW), Record13<Long?, Long?, Long?, String?, Int?, Long?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, String?> {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var projectId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open var creationTimestamp: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open var workflowType: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var lastStatus: Int
        set(value): Unit = set(4, value)
        get(): Int = get(4) as Int

    open var lastStatusRecordedTimestamp: Long
        set(value): Unit = set(5, value)
        get(): Long = get(5) as Long

    open var planInfo: JSONB
        set(value): Unit = set(6, value)
        get(): JSONB = get(6) as JSONB

    open var commitInfo: JSONB
        set(value): Unit = set(7, value)
        get(): JSONB = get(7) as JSONB

    open var requestedUserInputs: JSONB
        set(value): Unit = set(8, value)
        get(): JSONB = get(8) as JSONB

    open var valuedUserInputs: JSONB
        set(value): Unit = set(9, value)
        get(): JSONB = get(9) as JSONB

    open var buildArtifacts: JSONB
        set(value): Unit = set(10, value)
        get(): JSONB = get(10) as JSONB

    open var paramMap: JSONB?
        set(value): Unit = set(11, value)
        get(): JSONB? = get(11) as JSONB?

    open var idempotencyKey: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row13<Long?, Long?, Long?, String?, Int?, Long?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, String?> = super.fieldsRow() as Row13<Long?, Long?, Long?, String?, Int?, Long?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, String?>
    override fun valuesRow(): Row13<Long?, Long?, Long?, String?, Int?, Long?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, String?> = super.valuesRow() as Row13<Long?, Long?, Long?, String?, Int?, Long?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, JSONB?, String?>
    override fun field1(): Field<Long?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.ID
    override fun field2(): Field<Long?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.PROJECT_ID
    override fun field3(): Field<Long?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.CREATION_TIMESTAMP
    override fun field4(): Field<String?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.WORKFLOW_TYPE
    override fun field5(): Field<Int?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.LAST_STATUS
    override fun field6(): Field<Long?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.LAST_STATUS_RECORDED_TIMESTAMP
    override fun field7(): Field<JSONB?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.PLAN_INFO
    override fun field8(): Field<JSONB?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.COMMIT_INFO
    override fun field9(): Field<JSONB?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.REQUESTED_USER_INPUTS
    override fun field10(): Field<JSONB?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.VALUED_USER_INPUTS
    override fun field11(): Field<JSONB?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.BUILD_ARTIFACTS
    override fun field12(): Field<JSONB?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.PARAM_MAP
    override fun field13(): Field<String?> = com.arbr.db.`public`.tables.UserProjectWorkflow.USER_PROJECT_WORKFLOW.IDEMPOTENCY_KEY
    override fun component1(): Long? = id
    override fun component2(): Long = projectId
    override fun component3(): Long = creationTimestamp
    override fun component4(): String = workflowType
    override fun component5(): Int = lastStatus
    override fun component6(): Long = lastStatusRecordedTimestamp
    override fun component7(): JSONB = planInfo
    override fun component8(): JSONB = commitInfo
    override fun component9(): JSONB = requestedUserInputs
    override fun component10(): JSONB = valuedUserInputs
    override fun component11(): JSONB = buildArtifacts
    override fun component12(): JSONB? = paramMap
    override fun component13(): String? = idempotencyKey
    override fun value1(): Long? = id
    override fun value2(): Long = projectId
    override fun value3(): Long = creationTimestamp
    override fun value4(): String = workflowType
    override fun value5(): Int = lastStatus
    override fun value6(): Long = lastStatusRecordedTimestamp
    override fun value7(): JSONB = planInfo
    override fun value8(): JSONB = commitInfo
    override fun value9(): JSONB = requestedUserInputs
    override fun value10(): JSONB = valuedUserInputs
    override fun value11(): JSONB = buildArtifacts
    override fun value12(): JSONB? = paramMap
    override fun value13(): String? = idempotencyKey

    override fun value1(value: Long?): UserProjectWorkflowRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Long?): UserProjectWorkflowRecord {
        set(1, value)
        return this
    }

    override fun value3(value: Long?): UserProjectWorkflowRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): UserProjectWorkflowRecord {
        set(3, value)
        return this
    }

    override fun value5(value: Int?): UserProjectWorkflowRecord {
        set(4, value)
        return this
    }

    override fun value6(value: Long?): UserProjectWorkflowRecord {
        set(5, value)
        return this
    }

    override fun value7(value: JSONB?): UserProjectWorkflowRecord {
        set(6, value)
        return this
    }

    override fun value8(value: JSONB?): UserProjectWorkflowRecord {
        set(7, value)
        return this
    }

    override fun value9(value: JSONB?): UserProjectWorkflowRecord {
        set(8, value)
        return this
    }

    override fun value10(value: JSONB?): UserProjectWorkflowRecord {
        set(9, value)
        return this
    }

    override fun value11(value: JSONB?): UserProjectWorkflowRecord {
        set(10, value)
        return this
    }

    override fun value12(value: JSONB?): UserProjectWorkflowRecord {
        set(11, value)
        return this
    }

    override fun value13(value: String?): UserProjectWorkflowRecord {
        set(12, value)
        return this
    }

    override fun values(value1: Long?, value2: Long?, value3: Long?, value4: String?, value5: Int?, value6: Long?, value7: JSONB?, value8: JSONB?, value9: JSONB?, value10: JSONB?, value11: JSONB?, value12: JSONB?, value13: String?): UserProjectWorkflowRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        return this
    }

    /**
     * Create a detached, initialised UserProjectWorkflowRecord
     */
    constructor(id: Long? = null, projectId: Long, creationTimestamp: Long, workflowType: String, lastStatus: Int, lastStatusRecordedTimestamp: Long, planInfo: JSONB, commitInfo: JSONB, requestedUserInputs: JSONB, valuedUserInputs: JSONB, buildArtifacts: JSONB, paramMap: JSONB? = null, idempotencyKey: String? = null): this() {
        this.id = id
        this.projectId = projectId
        this.creationTimestamp = creationTimestamp
        this.workflowType = workflowType
        this.lastStatus = lastStatus
        this.lastStatusRecordedTimestamp = lastStatusRecordedTimestamp
        this.planInfo = planInfo
        this.commitInfo = commitInfo
        this.requestedUserInputs = requestedUserInputs
        this.valuedUserInputs = valuedUserInputs
        this.buildArtifacts = buildArtifacts
        this.paramMap = paramMap
        this.idempotencyKey = idempotencyKey
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised UserProjectWorkflowRecord
     */
    constructor(value: com.arbr.db.`public`.tables.pojos.UserProjectWorkflow?): this() {
        if (value != null) {
            this.id = value.id
            this.projectId = value.projectId
            this.creationTimestamp = value.creationTimestamp
            this.workflowType = value.workflowType
            this.lastStatus = value.lastStatus
            this.lastStatusRecordedTimestamp = value.lastStatusRecordedTimestamp
            this.planInfo = value.planInfo
            this.commitInfo = value.commitInfo
            this.requestedUserInputs = value.requestedUserInputs
            this.valuedUserInputs = value.valuedUserInputs
            this.buildArtifacts = value.buildArtifacts
            this.paramMap = value.paramMap
            this.idempotencyKey = value.idempotencyKey
            resetChangedOnNotNull()
        }
    }
}
