/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.records


import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserProjectWorkflowWorkerRecord private constructor() : UpdatableRecordImpl<UserProjectWorkflowWorkerRecord>(com.arbr.db.`public`.tables.UserProjectWorkflowWorker.USER_PROJECT_WORKFLOW_WORKER), Record4<Long?, Long?, Long?, String?> {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var creationTimestamp: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open var workflowId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var workerUuid: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row4<Long?, Long?, Long?, String?> = super.fieldsRow() as Row4<Long?, Long?, Long?, String?>
    override fun valuesRow(): Row4<Long?, Long?, Long?, String?> = super.valuesRow() as Row4<Long?, Long?, Long?, String?>
    override fun field1(): Field<Long?> = com.arbr.db.`public`.tables.UserProjectWorkflowWorker.USER_PROJECT_WORKFLOW_WORKER.ID
    override fun field2(): Field<Long?> = com.arbr.db.`public`.tables.UserProjectWorkflowWorker.USER_PROJECT_WORKFLOW_WORKER.CREATION_TIMESTAMP
    override fun field3(): Field<Long?> = com.arbr.db.`public`.tables.UserProjectWorkflowWorker.USER_PROJECT_WORKFLOW_WORKER.WORKFLOW_ID
    override fun field4(): Field<String?> = com.arbr.db.`public`.tables.UserProjectWorkflowWorker.USER_PROJECT_WORKFLOW_WORKER.WORKER_UUID
    override fun component1(): Long? = id
    override fun component2(): Long = creationTimestamp
    override fun component3(): Long? = workflowId
    override fun component4(): String? = workerUuid
    override fun value1(): Long? = id
    override fun value2(): Long = creationTimestamp
    override fun value3(): Long? = workflowId
    override fun value4(): String? = workerUuid

    override fun value1(value: Long?): UserProjectWorkflowWorkerRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Long?): UserProjectWorkflowWorkerRecord {
        set(1, value)
        return this
    }

    override fun value3(value: Long?): UserProjectWorkflowWorkerRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): UserProjectWorkflowWorkerRecord {
        set(3, value)
        return this
    }

    override fun values(value1: Long?, value2: Long?, value3: Long?, value4: String?): UserProjectWorkflowWorkerRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        return this
    }

    /**
     * Create a detached, initialised UserProjectWorkflowWorkerRecord
     */
    constructor(id: Long? = null, creationTimestamp: Long, workflowId: Long? = null, workerUuid: String? = null): this() {
        this.id = id
        this.creationTimestamp = creationTimestamp
        this.workflowId = workflowId
        this.workerUuid = workerUuid
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised UserProjectWorkflowWorkerRecord
     */
    constructor(value: com.arbr.db.`public`.tables.pojos.UserProjectWorkflowWorker?): this() {
        if (value != null) {
            this.id = value.id
            this.creationTimestamp = value.creationTimestamp
            this.workflowId = value.workflowId
            this.workerUuid = value.workerUuid
            resetChangedOnNotNull()
        }
    }
}
