package com.arbr.og.object_model.common.values

/**
 * Kind of sourced value.
 * Ordered by increased entropy such that combining two values should use the greater of the two.
 */
enum class SourcedValueKind : Comparable<SourcedValueKind> {
    /**
     * A constant value, usually hardcoded.
     */
    CONSTANT,

    /**
     * A value that exists as a real "materialized" object, such as the name of a file on disk.
     */
    MATERIALIZED,

    /**
     * A value from input such as user input.
     */
    INPUT,

    /**
     * A value generated by a completion application.
     */
    GENERATED,

    /**
     * A value computed via, but distinct from, its parent(s).
     */
    COMPUTED;
}