/*
 * This file is generated by jOOQ.
 */
package com.arbr.db


import com.arbr.db.datasets.Datasets

import kotlin.collections.List

import org.jooq.Constants
import org.jooq.Schema
import org.jooq.impl.CatalogImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultCatalog : CatalogImpl("") {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_CATALOG</code>
         */
        public val DEFAULT_CATALOG: DefaultCatalog = DefaultCatalog()
    }

    /**
     * The schema <code>datasets</code>.
     */
    val DATASETS: Datasets get(): Datasets = Datasets.DATASETS

    /**
     * The schema <code>public</code>.
     */
    val PUBLIC: com.arbr.db.`public`.Public get(): com.arbr.db.`public`.Public = com.arbr.db.`public`.Public.PUBLIC

    override fun getSchemas(): List<Schema> = listOf(
        Datasets.DATASETS,
        com.arbr.db.`public`.Public.PUBLIC
    )

    /**
     * A reference to the 3.18 minor release of the code generator. If this
     * doesn't compile, it's because the runtime library uses an older minor
     * release, namely: 3.18. You can turn off the generation of this reference
     * by specifying /configuration/generator/generate/jooqVersionReference
     */
    private val REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_18
}
