package com.arbr.platform.object_graph.common.functions.spec.base

import com.arbr.platform.object_graph.common.properties.NonNullRequirementsProvider

interface GraphObjectQueryMapContext: ResourceHelperFunctionInputSpecContext, NonNullRequirementsProvider
