package com.topdown.parsers.lang.ts.segmenter

import com.topdown.parsers.base.BaseLanguageFactory
import com.topdown.parsers.lang.ts.base.TypeScriptLexer
import com.topdown.parsers.lang.ts.base.TypeScriptParser
import com.topdown.parsers.lang.universal.tree_parsing.TreeParsingListener
import com.topdown.parsers.lang.universal.tree_parsing.UniversalTreeParsingListener
import org.antlr.v4.runtime.ANTLRErrorListener
import org.antlr.v4.runtime.CharStreams
import org.antlr.v4.runtime.CommonTokenStream
import org.antlr.v4.runtime.Lexer
import org.antlr.v4.runtime.tree.ParseTree

class TypeScriptSegmenter : BaseLanguageFactory {
    override fun lexerFromFileContents(fileContents: String): Lexer {
        return TypeScriptLexer(CharStreams.fromString(fileContents))
            .also { it.removeErrorListeners() }
    }

    override fun makeTreeParsingListener(contentLength: Long, tokens: CommonTokenStream): TreeParsingListener {
        // TODO: Support autogenerated tree parsing listeners
        return UniversalTreeParsingListener(contentLength)
    }

    override fun makeParseTree(commonTokenStream: CommonTokenStream, errorListener: ANTLRErrorListener): ParseTree {
        return TypeScriptParser(commonTokenStream)
            .also { it.removeErrorListeners() }
            .also { it.addErrorListener(errorListener) }
            .program()
    }
}
