/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables


import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IoPair(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, com.arbr.db.`public`.tables.records.IoPairRecord>?,
    aliased: Table<com.arbr.db.`public`.tables.records.IoPairRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<com.arbr.db.`public`.tables.records.IoPairRecord>(
    alias,
    com.arbr.db.`public`.Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.io_pair</code>
         */
        val IO_PAIR: IoPair = IoPair()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.arbr.db.`public`.tables.records.IoPairRecord> = com.arbr.db.`public`.tables.records.IoPairRecord::class.java

    /**
     * The column <code>public.io_pair.id</code>.
     */
    val ID: TableField<com.arbr.db.`public`.tables.records.IoPairRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.io_pair.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<com.arbr.db.`public`.tables.records.IoPairRecord, Long?> = createField(DSL.name("creation_timestamp"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.io_pair.input_resource_id</code>.
     */
    val INPUT_RESOURCE_ID: TableField<com.arbr.db.`public`.tables.records.IoPairRecord, Long?> = createField(DSL.name("input_resource_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.io_pair.output_resource_id</code>.
     */
    val OUTPUT_RESOURCE_ID: TableField<com.arbr.db.`public`.tables.records.IoPairRecord, Long?> = createField(DSL.name("output_resource_id"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.IoPairRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.IoPairRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.io_pair</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.io_pair</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.io_pair</code> table reference
     */
    constructor(): this(DSL.name("io_pair"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, com.arbr.db.`public`.tables.records.IoPairRecord>): this(Internal.createPathAlias(child, key), child, key, IO_PAIR, null)
    override fun getSchema(): Schema? = if (aliased()) null else com.arbr.db.`public`.Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(com.arbr.db.`public`.indexes.IO_PAIR_INPUT_RESOURCE_ID)
    override fun getIdentity(): Identity<com.arbr.db.`public`.tables.records.IoPairRecord, Long?> = super.getIdentity() as Identity<com.arbr.db.`public`.tables.records.IoPairRecord, Long?>
    override fun getReferences(): List<ForeignKey<com.arbr.db.`public`.tables.records.IoPairRecord, *>> = listOf(com.arbr.db.`public`.keys.IO_PAIR__IO_PAIR_INPUT_RESOURCE_ID_FKEY, com.arbr.db.`public`.keys.IO_PAIR__IO_PAIR_OUTPUT_RESOURCE_ID_FKEY)

    private lateinit var _ioPairInputResourceIdFkey: com.arbr.db.`public`.tables.IndexedResource
    private lateinit var _ioPairOutputResourceIdFkey: com.arbr.db.`public`.tables.IndexedResource

    /**
     * Get the implicit join path to the <code>public.indexed_resource</code>
     * table, via the <code>io_pair_input_resource_id_fkey</code> key.
     */
    fun ioPairInputResourceIdFkey(): com.arbr.db.`public`.tables.IndexedResource {
        if (!this::_ioPairInputResourceIdFkey.isInitialized)
            _ioPairInputResourceIdFkey = com.arbr.db.`public`.tables.IndexedResource(this, com.arbr.db.`public`.keys.IO_PAIR__IO_PAIR_INPUT_RESOURCE_ID_FKEY)

        return _ioPairInputResourceIdFkey;
    }

    val ioPairInputResourceIdFkey: com.arbr.db.`public`.tables.IndexedResource
        get(): com.arbr.db.`public`.tables.IndexedResource = ioPairInputResourceIdFkey()

    /**
     * Get the implicit join path to the <code>public.indexed_resource</code>
     * table, via the <code>io_pair_output_resource_id_fkey</code> key.
     */
    fun ioPairOutputResourceIdFkey(): com.arbr.db.`public`.tables.IndexedResource {
        if (!this::_ioPairOutputResourceIdFkey.isInitialized)
            _ioPairOutputResourceIdFkey = com.arbr.db.`public`.tables.IndexedResource(this, com.arbr.db.`public`.keys.IO_PAIR__IO_PAIR_OUTPUT_RESOURCE_ID_FKEY)

        return _ioPairOutputResourceIdFkey;
    }

    val ioPairOutputResourceIdFkey: com.arbr.db.`public`.tables.IndexedResource
        get(): com.arbr.db.`public`.tables.IndexedResource = ioPairOutputResourceIdFkey()
    override fun `as`(alias: String): IoPair = IoPair(DSL.name(alias), this)
    override fun `as`(alias: Name): IoPair = IoPair(alias, this)
    override fun `as`(alias: Table<*>): IoPair = IoPair(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): IoPair = IoPair(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): IoPair = IoPair(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): IoPair = IoPair(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Long?, Long?, Long?, Long?> = super.fieldsRow() as Row4<Long?, Long?, Long?, Long?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Long?, Long?, Long?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Long?, Long?, Long?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
