/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables


import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserAccountLinkAlphaCode(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord>?,
    aliased: Table<com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord>(
    alias,
    com.arbr.db.`public`.Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.user_account_link_alpha_code</code>
         */
        val USER_ACCOUNT_LINK_ALPHA_CODE: UserAccountLinkAlphaCode = UserAccountLinkAlphaCode()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord> = com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord::class.java

    /**
     * The column <code>public.user_account_link_alpha_code.user_id</code>.
     */
    val USER_ID: TableField<com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.user_account_link_alpha_code.code</code>.
     */
    val CODE: TableField<com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord, String?> = createField(DSL.name("code"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.user_account_link_alpha_code</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.user_account_link_alpha_code</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.user_account_link_alpha_code</code> table reference
     */
    constructor(): this(DSL.name("user_account_link_alpha_code"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord>): this(Internal.createPathAlias(child, key), child, key, USER_ACCOUNT_LINK_ALPHA_CODE, null)
    override fun getSchema(): Schema? = if (aliased()) null else com.arbr.db.`public`.Public.PUBLIC
    override fun getUniqueKeys(): List<UniqueKey<com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord>> = listOf(com.arbr.db.`public`.keys.USER_ACCOUNT_LINK_ALPHA_CODE_USER_ID_KEY, com.arbr.db.`public`.keys.USER_ACCOUNT_LINK_ALPHA_CODE_CODE_KEY)
    override fun getReferences(): List<ForeignKey<com.arbr.db.`public`.tables.records.UserAccountLinkAlphaCodeRecord, *>> = listOf(com.arbr.db.`public`.keys.USER_ACCOUNT_LINK_ALPHA_CODE__USER_ACCOUNT_LINK_ALPHA_CODE_USER_ID_FKEY, com.arbr.db.`public`.keys.USER_ACCOUNT_LINK_ALPHA_CODE__USER_ACCOUNT_LINK_ALPHA_CODE_CODE_FKEY)

    private lateinit var _userAccount: com.arbr.db.`public`.tables.UserAccount
    private lateinit var _alphaCode: com.arbr.db.`public`.tables.AlphaCode

    /**
     * Get the implicit join path to the <code>public.user_account</code> table.
     */
    fun userAccount(): com.arbr.db.`public`.tables.UserAccount {
        if (!this::_userAccount.isInitialized)
            _userAccount = com.arbr.db.`public`.tables.UserAccount(this, com.arbr.db.`public`.keys.USER_ACCOUNT_LINK_ALPHA_CODE__USER_ACCOUNT_LINK_ALPHA_CODE_USER_ID_FKEY)

        return _userAccount;
    }

    val userAccount: com.arbr.db.`public`.tables.UserAccount
        get(): com.arbr.db.`public`.tables.UserAccount = userAccount()

    /**
     * Get the implicit join path to the <code>public.alpha_code</code> table.
     */
    fun alphaCode(): com.arbr.db.`public`.tables.AlphaCode {
        if (!this::_alphaCode.isInitialized)
            _alphaCode = com.arbr.db.`public`.tables.AlphaCode(this, com.arbr.db.`public`.keys.USER_ACCOUNT_LINK_ALPHA_CODE__USER_ACCOUNT_LINK_ALPHA_CODE_CODE_FKEY)

        return _alphaCode;
    }

    val alphaCode: com.arbr.db.`public`.tables.AlphaCode
        get(): com.arbr.db.`public`.tables.AlphaCode = alphaCode()
    override fun `as`(alias: String): UserAccountLinkAlphaCode = UserAccountLinkAlphaCode(DSL.name(alias), this)
    override fun `as`(alias: Name): UserAccountLinkAlphaCode = UserAccountLinkAlphaCode(alias, this)
    override fun `as`(alias: Table<*>): UserAccountLinkAlphaCode = UserAccountLinkAlphaCode(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserAccountLinkAlphaCode = UserAccountLinkAlphaCode(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserAccountLinkAlphaCode = UserAccountLinkAlphaCode(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserAccountLinkAlphaCode = UserAccountLinkAlphaCode(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<Long?, String?> = super.fieldsRow() as Row2<Long?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
