/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables


import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserEmail(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserEmailRecord>?,
    aliased: Table<com.arbr.db.`public`.tables.records.UserEmailRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<com.arbr.db.`public`.tables.records.UserEmailRecord>(
    alias,
    com.arbr.db.`public`.Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.user_email</code>
         */
        val USER_EMAIL: UserEmail = UserEmail()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.arbr.db.`public`.tables.records.UserEmailRecord> = com.arbr.db.`public`.tables.records.UserEmailRecord::class.java

    /**
     * The column <code>public.user_email.user_id</code>.
     */
    val USER_ID: TableField<com.arbr.db.`public`.tables.records.UserEmailRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.user_email.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<com.arbr.db.`public`.tables.records.UserEmailRecord, Long?> = createField(DSL.name("creation_timestamp"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.user_email.updated_timestamp</code>.
     */
    val UPDATED_TIMESTAMP: TableField<com.arbr.db.`public`.tables.records.UserEmailRecord, Long?> = createField(DSL.name("updated_timestamp"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.user_email.email_address</code>.
     */
    val EMAIL_ADDRESS: TableField<com.arbr.db.`public`.tables.records.UserEmailRecord, String?> = createField(DSL.name("email_address"), SQLDataType.VARCHAR(511).nullable(false), this, "")

    /**
     * The column <code>public.user_email.source</code>.
     */
    val SOURCE: TableField<com.arbr.db.`public`.tables.records.UserEmailRecord, String?> = createField(DSL.name("source"), SQLDataType.VARCHAR(31).nullable(false), this, "")

    /**
     * The column <code>public.user_email.gh_verified</code>.
     */
    val GH_VERIFIED: TableField<com.arbr.db.`public`.tables.records.UserEmailRecord, Boolean?> = createField(DSL.name("gh_verified"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column <code>public.user_email.gh_primary</code>.
     */
    val GH_PRIMARY: TableField<com.arbr.db.`public`.tables.records.UserEmailRecord, Boolean?> = createField(DSL.name("gh_primary"), SQLDataType.BOOLEAN, this, "")

    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserEmailRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserEmailRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.user_email</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.user_email</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.user_email</code> table reference
     */
    constructor(): this(DSL.name("user_email"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserEmailRecord>): this(Internal.createPathAlias(child, key), child, key, USER_EMAIL, null)
    override fun getSchema(): Schema? = if (aliased()) null else com.arbr.db.`public`.Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(com.arbr.db.`public`.indexes.USER_EMAIL_EMAIL_ADDRESS, com.arbr.db.`public`.indexes.USER_EMAIL_USER_ID)
    override fun getUniqueKeys(): List<UniqueKey<com.arbr.db.`public`.tables.records.UserEmailRecord>> = listOf(com.arbr.db.`public`.keys.USER_EMAIL_USER_ID_EMAIL_ADDRESS_KEY)
    override fun getReferences(): List<ForeignKey<com.arbr.db.`public`.tables.records.UserEmailRecord, *>> = listOf(com.arbr.db.`public`.keys.USER_EMAIL__USER_EMAIL_USER_ID_FKEY)

    private lateinit var _userAccount: com.arbr.db.`public`.tables.UserAccount

    /**
     * Get the implicit join path to the <code>public.user_account</code> table.
     */
    fun userAccount(): com.arbr.db.`public`.tables.UserAccount {
        if (!this::_userAccount.isInitialized)
            _userAccount = com.arbr.db.`public`.tables.UserAccount(this, com.arbr.db.`public`.keys.USER_EMAIL__USER_EMAIL_USER_ID_FKEY)

        return _userAccount;
    }

    val userAccount: com.arbr.db.`public`.tables.UserAccount
        get(): com.arbr.db.`public`.tables.UserAccount = userAccount()
    override fun `as`(alias: String): UserEmail = UserEmail(DSL.name(alias), this)
    override fun `as`(alias: Name): UserEmail = UserEmail(alias, this)
    override fun `as`(alias: Table<*>): UserEmail = UserEmail(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserEmail = UserEmail(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserEmail = UserEmail(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserEmail = UserEmail(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row7<Long?, Long?, Long?, String?, String?, Boolean?, Boolean?> = super.fieldsRow() as Row7<Long?, Long?, Long?, String?, String?, Boolean?, Boolean?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Long?, Long?, String?, String?, Boolean?, Boolean?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Long?, Long?, String?, String?, Boolean?, Boolean?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
