/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables


import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserProject(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserProjectRecord>?,
    aliased: Table<com.arbr.db.`public`.tables.records.UserProjectRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<com.arbr.db.`public`.tables.records.UserProjectRecord>(
    alias,
    com.arbr.db.`public`.Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.user_project</code>
         */
        val USER_PROJECT: UserProject = UserProject()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.arbr.db.`public`.tables.records.UserProjectRecord> = com.arbr.db.`public`.tables.records.UserProjectRecord::class.java

    /**
     * The column <code>public.user_project.id</code>.
     */
    val ID: TableField<com.arbr.db.`public`.tables.records.UserProjectRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.user_project.user_id</code>.
     */
    val USER_ID: TableField<com.arbr.db.`public`.tables.records.UserProjectRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.user_project.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<com.arbr.db.`public`.tables.records.UserProjectRecord, Long?> = createField(DSL.name("creation_timestamp"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.user_project.full_name</code>.
     */
    val FULL_NAME: TableField<com.arbr.db.`public`.tables.records.UserProjectRecord, String?> = createField(DSL.name("full_name"), SQLDataType.VARCHAR(65535).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserProjectRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserProjectRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.user_project</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.user_project</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.user_project</code> table reference
     */
    constructor(): this(DSL.name("user_project"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserProjectRecord>): this(Internal.createPathAlias(child, key), child, key, USER_PROJECT, null)
    override fun getSchema(): Schema? = if (aliased()) null else com.arbr.db.`public`.Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(com.arbr.db.`public`.indexes.USER_PROJECT_ID_IDX)
    override fun getIdentity(): Identity<com.arbr.db.`public`.tables.records.UserProjectRecord, Long?> = super.getIdentity() as Identity<com.arbr.db.`public`.tables.records.UserProjectRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<com.arbr.db.`public`.tables.records.UserProjectRecord> = com.arbr.db.`public`.keys.USER_PROJECT_PKEY
    override fun getUniqueKeys(): List<UniqueKey<com.arbr.db.`public`.tables.records.UserProjectRecord>> = listOf(com.arbr.db.`public`.keys.USER_PROJECT_ID_KEY)
    override fun getReferences(): List<ForeignKey<com.arbr.db.`public`.tables.records.UserProjectRecord, *>> = listOf(com.arbr.db.`public`.keys.USER_PROJECT__USER_PROJECT_USER_ID_FKEY)

    private lateinit var _userAccount: com.arbr.db.`public`.tables.UserAccount

    /**
     * Get the implicit join path to the <code>public.user_account</code> table.
     */
    fun userAccount(): com.arbr.db.`public`.tables.UserAccount {
        if (!this::_userAccount.isInitialized)
            _userAccount = com.arbr.db.`public`.tables.UserAccount(this, com.arbr.db.`public`.keys.USER_PROJECT__USER_PROJECT_USER_ID_FKEY)

        return _userAccount;
    }

    val userAccount: com.arbr.db.`public`.tables.UserAccount
        get(): com.arbr.db.`public`.tables.UserAccount = userAccount()
    override fun `as`(alias: String): UserProject = UserProject(DSL.name(alias), this)
    override fun `as`(alias: Name): UserProject = UserProject(alias, this)
    override fun `as`(alias: Table<*>): UserProject = UserProject(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserProject = UserProject(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserProject = UserProject(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserProject = UserProject(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Long?, Long?, Long?, String?> = super.fieldsRow() as Row4<Long?, Long?, Long?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Long?, Long?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Long?, Long?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
