/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables


import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserProjectWorkflowEventStream(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord>?,
    aliased: Table<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord>(
    alias,
    com.arbr.db.`public`.Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.user_project_workflow_event_stream</code>
         */
        val USER_PROJECT_WORKFLOW_EVENT_STREAM: UserProjectWorkflowEventStream = UserProjectWorkflowEventStream()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord> = com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord::class.java

    /**
     * The column <code>public.user_project_workflow_event_stream.id</code>.
     */
    val ID: TableField<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column
     * <code>public.user_project_workflow_event_stream.workflow_id</code>.
     */
    val WORKFLOW_ID: TableField<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord, Long?> = createField(DSL.name("workflow_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column
     * <code>public.user_project_workflow_event_stream.topic_name</code>.
     */
    val TOPIC_NAME: TableField<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord, String?> = createField(DSL.name("topic_name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column
     * <code>public.user_project_workflow_event_stream.state_hash</code>.
     */
    val STATE_HASH: TableField<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord, String?> = createField(DSL.name("state_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column
     * <code>public.user_project_workflow_event_stream.ordinal_offset</code>.
     */
    val ORDINAL_OFFSET: TableField<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord, Long?> = createField(DSL.name("ordinal_offset"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column
     * <code>public.user_project_workflow_event_stream.event_timestamp</code>.
     */
    val EVENT_TIMESTAMP: TableField<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord, Long?> = createField(DSL.name("event_timestamp"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.user_project_workflow_event_stream</code>
     * table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.user_project_workflow_event_stream</code>
     * table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.user_project_workflow_event_stream</code> table
     * reference
     */
    constructor(): this(DSL.name("user_project_workflow_event_stream"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord>): this(Internal.createPathAlias(child, key), child, key, USER_PROJECT_WORKFLOW_EVENT_STREAM, null)
    override fun getSchema(): Schema? = if (aliased()) null else com.arbr.db.`public`.Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(com.arbr.db.`public`.indexes.USER_PROJECT_WORKFLOW_EVENT_STREAM_OFFSET_IDX, com.arbr.db.`public`.indexes.USER_PROJECT_WORKFLOW_EVENT_STREAM_STATE_HASH_IDX, com.arbr.db.`public`.indexes.USER_PROJECT_WORKFLOW_EVENT_STREAM_TOPIC_NAME_IDX, com.arbr.db.`public`.indexes.USER_PROJECT_WORKFLOW_EVENT_STREAM_WORKFLOW_ID_IDX)
    override fun getIdentity(): Identity<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord, Long?> = super.getIdentity() as Identity<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord> = com.arbr.db.`public`.keys.USER_PROJECT_WORKFLOW_EVENT_STREAM_PKEY
    override fun getReferences(): List<ForeignKey<com.arbr.db.`public`.tables.records.UserProjectWorkflowEventStreamRecord, *>> = listOf(com.arbr.db.`public`.keys.USER_PROJECT_WORKFLOW_EVENT_STREAM__USER_PROJECT_WORKFLOW_EVENT_STREAM_WORKFLOW_ID_FKEY)

    private lateinit var _userProjectWorkflow: com.arbr.db.`public`.tables.UserProjectWorkflow

    /**
     * Get the implicit join path to the
     * <code>public.user_project_workflow</code> table.
     */
    fun userProjectWorkflow(): com.arbr.db.`public`.tables.UserProjectWorkflow {
        if (!this::_userProjectWorkflow.isInitialized)
            _userProjectWorkflow = com.arbr.db.`public`.tables.UserProjectWorkflow(this, com.arbr.db.`public`.keys.USER_PROJECT_WORKFLOW_EVENT_STREAM__USER_PROJECT_WORKFLOW_EVENT_STREAM_WORKFLOW_ID_FKEY)

        return _userProjectWorkflow;
    }

    val userProjectWorkflow: com.arbr.db.`public`.tables.UserProjectWorkflow
        get(): com.arbr.db.`public`.tables.UserProjectWorkflow = userProjectWorkflow()
    override fun `as`(alias: String): UserProjectWorkflowEventStream = UserProjectWorkflowEventStream(DSL.name(alias), this)
    override fun `as`(alias: Name): UserProjectWorkflowEventStream = UserProjectWorkflowEventStream(alias, this)
    override fun `as`(alias: Table<*>): UserProjectWorkflowEventStream = UserProjectWorkflowEventStream(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserProjectWorkflowEventStream = UserProjectWorkflowEventStream(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserProjectWorkflowEventStream = UserProjectWorkflowEventStream(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserProjectWorkflowEventStream = UserProjectWorkflowEventStream(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Long?, Long?, String?, String?, Long?, Long?> = super.fieldsRow() as Row6<Long?, Long?, String?, String?, Long?, Long?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Long?, String?, String?, Long?, Long?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Long?, String?, String?, Long?, Long?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
