/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables


import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserProjectWorkflowWorker(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord>?,
    aliased: Table<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord>(
    alias,
    com.arbr.db.`public`.Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.user_project_workflow_worker</code>
         */
        val USER_PROJECT_WORKFLOW_WORKER: UserProjectWorkflowWorker = UserProjectWorkflowWorker()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord> = com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord::class.java

    /**
     * The column <code>public.user_project_workflow_worker.id</code>.
     */
    val ID: TableField<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column
     * <code>public.user_project_workflow_worker.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord, Long?> = createField(DSL.name("creation_timestamp"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.user_project_workflow_worker.workflow_id</code>.
     */
    val WORKFLOW_ID: TableField<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord, Long?> = createField(DSL.name("workflow_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.user_project_workflow_worker.worker_uuid</code>.
     */
    val WORKER_UUID: TableField<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord, String?> = createField(DSL.name("worker_uuid"), SQLDataType.VARCHAR(127), this, "")

    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.user_project_workflow_worker</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.user_project_workflow_worker</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.user_project_workflow_worker</code> table reference
     */
    constructor(): this(DSL.name("user_project_workflow_worker"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord>): this(Internal.createPathAlias(child, key), child, key, USER_PROJECT_WORKFLOW_WORKER, null)
    override fun getSchema(): Schema? = if (aliased()) null else com.arbr.db.`public`.Public.PUBLIC
    override fun getIdentity(): Identity<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord, Long?> = super.getIdentity() as Identity<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord> = com.arbr.db.`public`.keys.USER_PROJECT_WORKFLOW_WORKER_PKEY
    override fun getUniqueKeys(): List<UniqueKey<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord>> = listOf(com.arbr.db.`public`.keys.USER_PROJECT_WORKFLOW_WORKER_WORKFLOW_ID_KEY)
    override fun getReferences(): List<ForeignKey<com.arbr.db.`public`.tables.records.UserProjectWorkflowWorkerRecord, *>> = listOf(com.arbr.db.`public`.keys.USER_PROJECT_WORKFLOW_WORKER__USER_PROJECT_WORKFLOW_WORKER_WORKFLOW_ID_FKEY)

    private lateinit var _userProjectWorkflow: com.arbr.db.`public`.tables.UserProjectWorkflow

    /**
     * Get the implicit join path to the
     * <code>public.user_project_workflow</code> table.
     */
    fun userProjectWorkflow(): com.arbr.db.`public`.tables.UserProjectWorkflow {
        if (!this::_userProjectWorkflow.isInitialized)
            _userProjectWorkflow = com.arbr.db.`public`.tables.UserProjectWorkflow(this, com.arbr.db.`public`.keys.USER_PROJECT_WORKFLOW_WORKER__USER_PROJECT_WORKFLOW_WORKER_WORKFLOW_ID_FKEY)

        return _userProjectWorkflow;
    }

    val userProjectWorkflow: com.arbr.db.`public`.tables.UserProjectWorkflow
        get(): com.arbr.db.`public`.tables.UserProjectWorkflow = userProjectWorkflow()
    override fun `as`(alias: String): UserProjectWorkflowWorker = UserProjectWorkflowWorker(DSL.name(alias), this)
    override fun `as`(alias: Name): UserProjectWorkflowWorker = UserProjectWorkflowWorker(alias, this)
    override fun `as`(alias: Table<*>): UserProjectWorkflowWorker = UserProjectWorkflowWorker(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserProjectWorkflowWorker = UserProjectWorkflowWorker(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserProjectWorkflowWorker = UserProjectWorkflowWorker(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserProjectWorkflowWorker = UserProjectWorkflowWorker(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Long?, Long?, Long?, String?> = super.fieldsRow() as Row4<Long?, Long?, Long?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Long?, Long?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Long?, Long?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
