/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables


import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserEvent(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserEventRecord>?,
    aliased: Table<com.arbr.db.`public`.tables.records.UserEventRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<com.arbr.db.`public`.tables.records.UserEventRecord>(
    alias,
    com.arbr.db.`public`.Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.user_event</code>
         */
        val USER_EVENT: UserEvent = UserEvent()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.arbr.db.`public`.tables.records.UserEventRecord> = com.arbr.db.`public`.tables.records.UserEventRecord::class.java

    /**
     * The column <code>public.user_event.user_id</code>.
     */
    val USER_ID: TableField<com.arbr.db.`public`.tables.records.UserEventRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.user_event.event_timestamp</code>.
     */
    val EVENT_TIMESTAMP: TableField<com.arbr.db.`public`.tables.records.UserEventRecord, Long?> = createField(DSL.name("event_timestamp"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.user_event.event_name</code>.
     */
    val EVENT_NAME: TableField<com.arbr.db.`public`.tables.records.UserEventRecord, String?> = createField(DSL.name("event_name"), SQLDataType.VARCHAR(511).nullable(false), this, "")

    /**
     * The column <code>public.user_event.event_properties</code>.
     */
    val EVENT_PROPERTIES: TableField<com.arbr.db.`public`.tables.records.UserEventRecord, JSONB?> = createField(DSL.name("event_properties"), SQLDataType.JSONB, this, "")

    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserEventRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<com.arbr.db.`public`.tables.records.UserEventRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.user_event</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.user_event</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.user_event</code> table reference
     */
    constructor(): this(DSL.name("user_event"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, com.arbr.db.`public`.tables.records.UserEventRecord>): this(Internal.createPathAlias(child, key), child, key, USER_EVENT, null)
    override fun getSchema(): Schema? = if (aliased()) null else com.arbr.db.`public`.Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(com.arbr.db.`public`.indexes.USER_EVENT_USER_ID)
    override fun getReferences(): List<ForeignKey<com.arbr.db.`public`.tables.records.UserEventRecord, *>> = listOf(com.arbr.db.`public`.keys.USER_EVENT__USER_EVENT_USER_ID_FKEY)

    private lateinit var _userAccount: com.arbr.db.`public`.tables.UserAccount

    /**
     * Get the implicit join path to the <code>public.user_account</code> table.
     */
    fun userAccount(): com.arbr.db.`public`.tables.UserAccount {
        if (!this::_userAccount.isInitialized)
            _userAccount = com.arbr.db.`public`.tables.UserAccount(this, com.arbr.db.`public`.keys.USER_EVENT__USER_EVENT_USER_ID_FKEY)

        return _userAccount;
    }

    val userAccount: com.arbr.db.`public`.tables.UserAccount
        get(): com.arbr.db.`public`.tables.UserAccount = userAccount()
    override fun `as`(alias: String): UserEvent = UserEvent(DSL.name(alias), this)
    override fun `as`(alias: Name): UserEvent = UserEvent(alias, this)
    override fun `as`(alias: Table<*>): UserEvent = UserEvent(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserEvent = UserEvent(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserEvent = UserEvent(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserEvent = UserEvent(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Long?, Long?, String?, JSONB?> = super.fieldsRow() as Row4<Long?, Long?, String?, JSONB?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Long?, String?, JSONB?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Long?, String?, JSONB?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
