/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.pojos


import java.io.Serializable

import org.jooq.JSONB


/**
 * Input-Output pairs of Embedded Resources
 */
@Suppress("UNCHECKED_CAST")
data class EmbeddedResourcePair(
    val inputResourceId: Long? = null,
    val inputCreationTimestamp: Long? = null,
    val inputSchemaId: String? = null,
    val inputResourceObject: JSONB? = null,
    val inputChatMessages: JSONB? = null,
    val vectorId: String? = null,
    val embeddingKind: String? = null,
    val embeddingContent: String? = null,
    val metadata: JSONB? = null,
    val outputResourceId: Long? = null,
    val outputCreationTimestamp: Long? = null,
    val outputSchemaId: String? = null,
    val outputResourceObject: JSONB? = null,
    val outputChatMessages: JSONB? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: EmbeddedResourcePair = other as EmbeddedResourcePair
        if (this.inputResourceId == null) {
            if (o.inputResourceId != null)
                return false
        }
        else if (this.inputResourceId != o.inputResourceId)
            return false
        if (this.inputCreationTimestamp == null) {
            if (o.inputCreationTimestamp != null)
                return false
        }
        else if (this.inputCreationTimestamp != o.inputCreationTimestamp)
            return false
        if (this.inputSchemaId == null) {
            if (o.inputSchemaId != null)
                return false
        }
        else if (this.inputSchemaId != o.inputSchemaId)
            return false
        if (this.inputResourceObject == null) {
            if (o.inputResourceObject != null)
                return false
        }
        else if (this.inputResourceObject != o.inputResourceObject)
            return false
        if (this.inputChatMessages == null) {
            if (o.inputChatMessages != null)
                return false
        }
        else if (this.inputChatMessages != o.inputChatMessages)
            return false
        if (this.vectorId == null) {
            if (o.vectorId != null)
                return false
        }
        else if (this.vectorId != o.vectorId)
            return false
        if (this.embeddingKind == null) {
            if (o.embeddingKind != null)
                return false
        }
        else if (this.embeddingKind != o.embeddingKind)
            return false
        if (this.embeddingContent == null) {
            if (o.embeddingContent != null)
                return false
        }
        else if (this.embeddingContent != o.embeddingContent)
            return false
        if (this.metadata == null) {
            if (o.metadata != null)
                return false
        }
        else if (this.metadata != o.metadata)
            return false
        if (this.outputResourceId == null) {
            if (o.outputResourceId != null)
                return false
        }
        else if (this.outputResourceId != o.outputResourceId)
            return false
        if (this.outputCreationTimestamp == null) {
            if (o.outputCreationTimestamp != null)
                return false
        }
        else if (this.outputCreationTimestamp != o.outputCreationTimestamp)
            return false
        if (this.outputSchemaId == null) {
            if (o.outputSchemaId != null)
                return false
        }
        else if (this.outputSchemaId != o.outputSchemaId)
            return false
        if (this.outputResourceObject == null) {
            if (o.outputResourceObject != null)
                return false
        }
        else if (this.outputResourceObject != o.outputResourceObject)
            return false
        if (this.outputChatMessages == null) {
            if (o.outputChatMessages != null)
                return false
        }
        else if (this.outputChatMessages != o.outputChatMessages)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.inputResourceId == null) 0 else this.inputResourceId.hashCode())
        result = prime * result + (if (this.inputCreationTimestamp == null) 0 else this.inputCreationTimestamp.hashCode())
        result = prime * result + (if (this.inputSchemaId == null) 0 else this.inputSchemaId.hashCode())
        result = prime * result + (if (this.inputResourceObject == null) 0 else this.inputResourceObject.hashCode())
        result = prime * result + (if (this.inputChatMessages == null) 0 else this.inputChatMessages.hashCode())
        result = prime * result + (if (this.vectorId == null) 0 else this.vectorId.hashCode())
        result = prime * result + (if (this.embeddingKind == null) 0 else this.embeddingKind.hashCode())
        result = prime * result + (if (this.embeddingContent == null) 0 else this.embeddingContent.hashCode())
        result = prime * result + (if (this.metadata == null) 0 else this.metadata.hashCode())
        result = prime * result + (if (this.outputResourceId == null) 0 else this.outputResourceId.hashCode())
        result = prime * result + (if (this.outputCreationTimestamp == null) 0 else this.outputCreationTimestamp.hashCode())
        result = prime * result + (if (this.outputSchemaId == null) 0 else this.outputSchemaId.hashCode())
        result = prime * result + (if (this.outputResourceObject == null) 0 else this.outputResourceObject.hashCode())
        result = prime * result + (if (this.outputChatMessages == null) 0 else this.outputChatMessages.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("EmbeddedResourcePair (")

        sb.append(inputResourceId)
        sb.append(", ").append(inputCreationTimestamp)
        sb.append(", ").append(inputSchemaId)
        sb.append(", ").append(inputResourceObject)
        sb.append(", ").append(inputChatMessages)
        sb.append(", ").append(vectorId)
        sb.append(", ").append(embeddingKind)
        sb.append(", ").append(embeddingContent)
        sb.append(", ").append(metadata)
        sb.append(", ").append(outputResourceId)
        sb.append(", ").append(outputCreationTimestamp)
        sb.append(", ").append(outputSchemaId)
        sb.append(", ").append(outputResourceObject)
        sb.append(", ").append(outputChatMessages)

        sb.append(")")
        return sb.toString()
    }
}
