/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.pojos


import java.io.Serializable

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class IndexedResource(
    val id: Long? = null,
    val creationTimestamp: Long,
    val schemaId: String,
    val resourceObject: JSONB,
    val chatMessages: JSONB? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: IndexedResource = other as IndexedResource
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.creationTimestamp != o.creationTimestamp)
            return false
        if (this.schemaId != o.schemaId)
            return false
        if (this.resourceObject != o.resourceObject)
            return false
        if (this.chatMessages == null) {
            if (o.chatMessages != null)
                return false
        }
        else if (this.chatMessages != o.chatMessages)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.creationTimestamp.hashCode()
        result = prime * result + this.schemaId.hashCode()
        result = prime * result + this.resourceObject.hashCode()
        result = prime * result + (if (this.chatMessages == null) 0 else this.chatMessages.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("IndexedResource (")

        sb.append(id)
        sb.append(", ").append(creationTimestamp)
        sb.append(", ").append(schemaId)
        sb.append(", ").append(resourceObject)
        sb.append(", ").append(chatMessages)

        sb.append(")")
        return sb.toString()
    }
}
