/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class UserAccount(
    val id: Long? = null,
    val creationTimestamp: Long,
    val username: String? = null,
    val email: String? = null,
    val passwordKey: String,
    val rolesBitmask: Int,
    val avatarUrl: String? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: UserAccount = other as UserAccount
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.creationTimestamp != o.creationTimestamp)
            return false
        if (this.username == null) {
            if (o.username != null)
                return false
        }
        else if (this.username != o.username)
            return false
        if (this.email == null) {
            if (o.email != null)
                return false
        }
        else if (this.email != o.email)
            return false
        if (this.passwordKey != o.passwordKey)
            return false
        if (this.rolesBitmask != o.rolesBitmask)
            return false
        if (this.avatarUrl == null) {
            if (o.avatarUrl != null)
                return false
        }
        else if (this.avatarUrl != o.avatarUrl)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.creationTimestamp.hashCode()
        result = prime * result + (if (this.username == null) 0 else this.username.hashCode())
        result = prime * result + (if (this.email == null) 0 else this.email.hashCode())
        result = prime * result + this.passwordKey.hashCode()
        result = prime * result + this.rolesBitmask.hashCode()
        result = prime * result + (if (this.avatarUrl == null) 0 else this.avatarUrl.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("UserAccount (")

        sb.append(id)
        sb.append(", ").append(creationTimestamp)
        sb.append(", ").append(username)
        sb.append(", ").append(email)
        sb.append(", ").append(passwordKey)
        sb.append(", ").append(rolesBitmask)
        sb.append(", ").append(avatarUrl)

        sb.append(")")
        return sb.toString()
    }
}
