/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class UserProjectWorkflowWorker(
    val id: Long? = null,
    val creationTimestamp: Long,
    val workflowId: Long? = null,
    val workerUuid: String? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: UserProjectWorkflowWorker = other as UserProjectWorkflowWorker
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.creationTimestamp != o.creationTimestamp)
            return false
        if (this.workflowId == null) {
            if (o.workflowId != null)
                return false
        }
        else if (this.workflowId != o.workflowId)
            return false
        if (this.workerUuid == null) {
            if (o.workerUuid != null)
                return false
        }
        else if (this.workerUuid != o.workerUuid)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.creationTimestamp.hashCode()
        result = prime * result + (if (this.workflowId == null) 0 else this.workflowId.hashCode())
        result = prime * result + (if (this.workerUuid == null) 0 else this.workerUuid.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("UserProjectWorkflowWorker (")

        sb.append(id)
        sb.append(", ").append(creationTimestamp)
        sb.append(", ").append(workflowId)
        sb.append(", ").append(workerUuid)

        sb.append(")")
        return sb.toString()
    }
}
