/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class UserEmail(
    val userId: Long,
    val creationTimestamp: Long,
    val updatedTimestamp: Long,
    val emailAddress: String,
    val source: String,
    val ghVerified: Boolean? = null,
    val ghPrimary: Boolean? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: UserEmail = other as UserEmail
        if (this.userId != o.userId)
            return false
        if (this.creationTimestamp != o.creationTimestamp)
            return false
        if (this.updatedTimestamp != o.updatedTimestamp)
            return false
        if (this.emailAddress != o.emailAddress)
            return false
        if (this.source != o.source)
            return false
        if (this.ghVerified == null) {
            if (o.ghVerified != null)
                return false
        }
        else if (this.ghVerified != o.ghVerified)
            return false
        if (this.ghPrimary == null) {
            if (o.ghPrimary != null)
                return false
        }
        else if (this.ghPrimary != o.ghPrimary)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.userId.hashCode()
        result = prime * result + this.creationTimestamp.hashCode()
        result = prime * result + this.updatedTimestamp.hashCode()
        result = prime * result + this.emailAddress.hashCode()
        result = prime * result + this.source.hashCode()
        result = prime * result + (if (this.ghVerified == null) 0 else this.ghVerified.hashCode())
        result = prime * result + (if (this.ghPrimary == null) 0 else this.ghPrimary.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("UserEmail (")

        sb.append(userId)
        sb.append(", ").append(creationTimestamp)
        sb.append(", ").append(updatedTimestamp)
        sb.append(", ").append(emailAddress)
        sb.append(", ").append(source)
        sb.append(", ").append(ghVerified)
        sb.append(", ").append(ghPrimary)

        sb.append(")")
        return sb.toString()
    }
}
