/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class UserAccountLinkGithub(
    val creationTimestamp: Long,
    val githubId: String? = null,
    val githubKey: String? = null,
    val githubAppName: String? = null,
    val userId: Long
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: UserAccountLinkGithub = other as UserAccountLinkGithub
        if (this.creationTimestamp != o.creationTimestamp)
            return false
        if (this.githubId == null) {
            if (o.githubId != null)
                return false
        }
        else if (this.githubId != o.githubId)
            return false
        if (this.githubKey == null) {
            if (o.githubKey != null)
                return false
        }
        else if (this.githubKey != o.githubKey)
            return false
        if (this.githubAppName == null) {
            if (o.githubAppName != null)
                return false
        }
        else if (this.githubAppName != o.githubAppName)
            return false
        if (this.userId != o.userId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.creationTimestamp.hashCode()
        result = prime * result + (if (this.githubId == null) 0 else this.githubId.hashCode())
        result = prime * result + (if (this.githubKey == null) 0 else this.githubKey.hashCode())
        result = prime * result + (if (this.githubAppName == null) 0 else this.githubAppName.hashCode())
        result = prime * result + this.userId.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("UserAccountLinkGithub (")

        sb.append(creationTimestamp)
        sb.append(", ").append(githubId)
        sb.append(", ").append(githubKey)
        sb.append(", ").append(githubAppName)
        sb.append(", ").append(userId)

        sb.append(")")
        return sb.toString()
    }
}
