/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.pojos


import java.io.Serializable

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class UserEvent(
    val userId: Long,
    val eventTimestamp: Long,
    val eventName: String,
    val eventProperties: JSONB? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: UserEvent = other as UserEvent
        if (this.userId != o.userId)
            return false
        if (this.eventTimestamp != o.eventTimestamp)
            return false
        if (this.eventName != o.eventName)
            return false
        if (this.eventProperties == null) {
            if (o.eventProperties != null)
                return false
        }
        else if (this.eventProperties != o.eventProperties)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.userId.hashCode()
        result = prime * result + this.eventTimestamp.hashCode()
        result = prime * result + this.eventName.hashCode()
        result = prime * result + (if (this.eventProperties == null) 0 else this.eventProperties.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("UserEvent (")

        sb.append(userId)
        sb.append(", ").append(eventTimestamp)
        sb.append(", ").append(eventName)
        sb.append(", ").append(eventProperties)

        sb.append(")")
        return sb.toString()
    }
}
