/*
 * This file is generated by jOOQ.
 */
package com.arbr.db.`public`.tables.pojos


import com.arbr.db.binding.Vector1536

import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class VectorEmbedding(
    val vectorId: String,
    val namespace: String,
    val versionId: String,
    val schemaId: String,
    val embeddingContent: String,
    val embedding: Vector1536
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: VectorEmbedding = other as VectorEmbedding
        if (this.vectorId != o.vectorId)
            return false
        if (this.namespace != o.namespace)
            return false
        if (this.versionId != o.versionId)
            return false
        if (this.schemaId != o.schemaId)
            return false
        if (this.embeddingContent != o.embeddingContent)
            return false
        if (this.embedding != o.embedding)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.vectorId.hashCode()
        result = prime * result + this.namespace.hashCode()
        result = prime * result + this.versionId.hashCode()
        result = prime * result + this.schemaId.hashCode()
        result = prime * result + this.embeddingContent.hashCode()
        result = prime * result + this.embedding.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("VectorEmbedding (")

        sb.append(vectorId)
        sb.append(", ").append(namespace)
        sb.append(", ").append(versionId)
        sb.append(", ").append(schemaId)
        sb.append(", ").append(embeddingContent)
        sb.append(", ").append(embedding)

        sb.append(")")
        return sb.toString()
    }
}
